# Generated by Django 5.1 on 2025-01-02 15:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='food')),
                ('city', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('notes', models.TextField(null=True)),
                ('products', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='foodDelivery.cartitem')),
            ],
        ),
    ]
