# Generated by Django 5.1 on 2024-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_rename_meals_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to='foods/'),
        ),
    ]
