# Generated by Django 5.1 on 2024-09-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0003_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='image',
        ),
    ]
