# Generated by Django 5.1 on 2024-09-24 12:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0004_remove_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank='True', max_length=255, verbose_name='foods'),
        ),
    ]
