# Generated by Django 5.1 on 2025-02-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0005_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
