# Generated by Django 5.1 on 2025-09-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='items'),
        ),
    ]
